AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Respond to a web hook and create or update a PR for a boat in github.
Resources:
  lambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Respond to a web hook and create or update a PR for a boat in github.
      FunctionName: web-edit-boat-to-github
      Handler: lambda_function.lambda_handler
      Runtime: python3.13
      InlineCode: >-
        import json
        def lambda_handler(event, context):
          print(json.dumps(event))
      MemorySize: 128
      Timeout: 3
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
      Policies:
        - S3CrudPolicy:
            BucketName: boatregister
        - SSMParameterReadPolicy:
            ParameterName: GITHUB_TOKEN
  lambdaUrl:
    Type: AWS::Lambda::Url
    Properties: 
      AuthType: NONE
      InvokeMode: BUFFERED
      Cors:
        AllowCredentials: false
        AllowHeaders: 
          - content-type
        AllowMethods: 
          - POST
        AllowOrigins: 
          - http://localhost:3000
          - https://www.oga.org.uk
          - https://oga.org.uk
        MaxAge: 3
      TargetFunctionArn: !Ref lambda
  lambdaUrlFunctionPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref lambda
      Action: lambda:InvokeFunctionUrl
      Principal: "*"
      FunctionUrlAuthType: NONE
